### PR TITLE
Added support for actor per request

### PR DESCRIPTION
**Pull request by maxkorolev**
Hi, here is implemented idea of actor per request, inspired of [Spray Actor Per Request](https://github.com/NET-A-PORTER/spray-actor-per-request)
I think it's a good little step to make bootzooka be able to distribute. UserFinder, UserRegistrator, UserChanger are just workers which could create as [routees](http://doc.akka.io/docs/akka/current/scala/routing.html) or create on cluster. 
I am sorry I dropped UserService I think that with actors functionality seems more separate

### CODE REVIEW

**Comment by adamw** [comment]
Thanks a lot for the PR! It's certainly interesting to see how the actor-per-request pattern can be implemented here, and this could be a great example of an application structured that way, however I'm not sure if this is the best approach for a template application which strives to provide the absolute basics. Or maybe you think the actor-per-request pattern has some advantages and that it should be always used?

**Comment by maxkorolev** [comment]
Thank you for reply! The main idea is not only to implement actor-per-request pattern, it's just the way to distinguish parts of business logic.
Each worker has its own API which could be approximated to http responses.
If you we have one big service, some time past, we have a lof of.... well you know)
Are workers small fast appearing and dying microservices? - Maybe, why not)
Another advantage is to make workers persistent, with state of Event we can start build event sourcing

**Comment by adamw** [comment]
I'm sure such approach has advantages, but my doubt is whether it is suitable for a skeleton web app like Bootzooka?

Definitely I wouldn't want to see the services grow too big - but I am reluctant to go with actors, as this seems quite heavy (quite a lot of additional code) for a simple task. Maybe you have some suggestions as to how to avoid big services without going full-in with actors?

**Comment by maxkorolev** [comment]
Well ok, there are two suggestions in this PR:
1. Whole business logic should be placed in several small actors
2. Bring api between http layer and business layer

I agree that actors are not suitable here
You have already had UserRegisterResult and this is UserService's api, but each function returns different results like `Future[UserRegisterResult]`, `Future[Option[BasicUserData]]` and `Future[Either[String, Unit]]`. Because of that you have to write these big match in your routes

`case UserRegisterResult.InvalidData(msg) => complete(StatusCodes.BadRequest, msg)`
`case UserRegisterResult.UserExists(msg) => complete(StatusCodes.Conflict, msg)`
`case UserRegisterResult.Success => complete("success")`


But if you had [one general](https://github.com/maxkorolev/bootzooka/blob/master/backend%2Fsrc%2Fmain%2Fscala%2Fcom%2Fsoftwaremill%2Fbootzooka%2Futils%2Fhttp%2FPerRequest.scala#L35) way to talk each api user of UserService what you returned, you could write less code with [common matcher](https://github.com/maxkorolev/bootzooka/blob/master/backend%2Fsrc%2Fmain%2Fscala%2Fcom%2Fsoftwaremill%2Fbootzooka%2Futils%2Fhttp%2FRoutesSupport.scala#L42), and then, would painless divide UserService on several small services with one general api
I can show what I mean

**Comment by adamw** [comment]
But then, you need this additional layer which translates the service method call's result type to your result? Don't you in effect build a custom HTTP response types abstraction?

**Comment by maxkorolev** [comment]
Yes, I need a [small directive](https://github.com/maxkorolev/bootzooka/blob/master/backend/src/main/scala/com/softwaremill/bootzooka/utils/http/RoutesSupport.scala#L41) which translates my Events to HTTP responses, it's just DRY. If you want to support whole set of HTTP responses you wil have to write in routes each responce's translation, like `case UserRegisterResult.InvalidData(msg) => complete(StatusCodes.BadRequest, msg)`, and then routes will grow.
You already have such api, but you are using `Either` and `Option`. I think they are excessively general, returning `Left[String]` you don't send type of error, just description.
Well we are in context of bootzooka, and sure I wrong imposing my opinion in architecture.

**Comment by adamw** [comment]
My point was that you are building a HTTP-response-like layer of abstraction (`JustOk`, `Forbidden` etc.). If the service method calls/actors return these values, the HTTP aspect kind of creeps into the business logic - e.g. the `UserChanger` "knows" that there's a concept of a "Forbidden" response, not just that it's returning a description of the result.

Now there's another thing to consider: whether business logic should return a fully structured result (a custom ADT), or are we fine with more generic (e.g. `Either[String, Unit]`). The first approach is tempting, but can lead to quite a lot of additional code; the second approach makes use of existing abstractions, but might be less obvious to read. I think currently in bootzooka the structured approach is taken when the structure is later used (as with `registerNewUser), the `Either` approach when the error is handled generically. Do you maybe know of some resources which discuss both approaches and their advantages?

By the way, thanks for the discussion, I don't think imposing architectures is wrong, but I hope that discussing and not agreeing on some points is fine either :)

**Comment by maxkorolev** [comment]
Yes that's what I'm talking about, I liked HTTP-response-like behavior here. It's not because of we make HTTP service. I would use it for communication between services, it would be simple to transform messages to HTTP responses for communicating with services written on another languages, for example.

I've got your point, no, unfortunately, I didn't see any conversation on this topic maybe because of too common. I agree that first approach needs more code. Use it or not, as always "it depends on".
Thank you very much for bootzooka. Thank you for discussion!

**Pull request closed without merging**
