### PR TITLE
Fix missing autoprefixer dependency

### PR DESCRIPTION
**Pull request by pawelprazak**
I had to add this dependency for the `npm start` to work the first time.

You should be able to reproduce by (**deletes files!**):
```
$ git clean -fxd -e .idea
$ ./frontend-start.sh
```

### CODE REVIEW

**Comment by hanskoff** [comment]
can you please be more specific? I don't see any `missing autoprefixer dependency` (even when deleting untracked files)

**Comment by pawelprazak** [comment]
```
cd ui
rm -rf node_modules/
npm install
npm start
```
```
> @ start /home/pawel/repos/bootzooka/ui
> webpack-dev-server --content-base app --port 9090 --open

module.js:327
    throw err;
    ^

Error: Cannot find module 'autoprefixer'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/pawel/repos/bootzooka/ui/webpack.config.js:3:20)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

npm ERR! Linux 3.13.0-85-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE
npm ERR! @ start: `webpack-dev-server --content-base app --port 9090 --open`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ start script 'webpack-dev-server --content-base app --port 9090 --open'.
npm ERR! This is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --content-base app --port 9090 --open
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs 
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pawel/repos/bootzooka/ui/npm-debug.log
```
```
npm install --save-dev autoprefixer
npm start
```
```
> @ start /home/pawel/repos/bootzooka/ui
> webpack-dev-server --content-base app --port 9090 --open

http://localhost:9090/webpack-dev-server/
webpack result is served from /
content is served from /home/pawel/repos/bootzooka/ui/app
...
```

**Comment by hanskoff** [comment]
thanks for that check, I don't see that problem, could you please install node version >=5 and check again?

**Comment by pawelprazak** [comment]
Yes, it works on node.js 5

**Comment by hanskoff** [comment]
I've changed requirements here http://softwaremill.github.io/bootzooka/development.html and here http://softwaremill.github.io/bootzooka/frontend.html, so this should handle issue, thanks for reporting that

**Pull request closed without merging**
